# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_info',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='post_info',
            name='no_of_likes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_info',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
