# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_info',
            name='company',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
